create table if not exists public."Street"
(
    "Id"          integer generated by default as identity
        constraint "PK_Street"
            primary key,
    "Name"        varchar(256)                           not null,
    "Geometry"    geometry                               not null,
    "Capacity"    integer                                not null,
    "CreatedDate" timestamp with time zone default now() not null,
    "IsDeleted"   boolean                                not null
);

alter table public."Street"
    owner to dbuser;

